<?php

namespace ServerBundle\Repository;

/**
 * defaultConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class defaultConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
