UserBundle\Entity\Action:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\ActionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        action:
            type: text
            column: Action
        user:
            type: string
            length: 255
            column: User
        owner:
            type: string
            length: 255
            column: Owner
        ownerId:
            type: integer
            length: 255
            column: ownerId

    lifecycleCallbacks: {  }
