adminNetworkCreate:
      path: /admin/network/create
      controller: App\Controller\Admin\Network\AdminNetworkServerController::createNetworkServer
adminNetworkTest:
      path: /admin/network/{id}/test
      controller: App\Controller\Admin\Network\AdminNetworkServerController::testNetworkServerConnectionAPI