<?php

namespace ServerBundle\Repository;

/**
 * GameServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameServerRepository extends \Doctrine\ORM\EntityRepository
{
}
