<?php

namespace AppBundle\Repository;

/**
 * NetworkServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkServerRepository extends \Doctrine\ORM\EntityRepository
{
}
