api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

server:
    resource: "@ServerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
