# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        user_db_provider:
            entity:
                class: AppBundle:User
                property: username
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 10

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            guard:
                authenticators:
                    - AppBundle\Security\LoginAuthenticator
        api:
            pattern: ^/api/v1/
            anonymous: ~
            provider: user_db_provider
            security: false
#            guard:
#                authenticators:
#                    - AppBundle\Security\LoginAuthenticator


    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_USER }

