<?php

namespace AppBundle\Repository;

/**
 * ServerTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
