AppBundle\Entity\ServerTemplate:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ServerTemplateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        networkId:
            type: integer
        configId:
            type: integer
        steamPercentage:
            type: string
            length: 255
            column: steam_percentage
        steam_name:
            type: string
            length: 255
        template_name:
            type: string
            length: 255
        dateCreated:
            type: string
            length: 255
            column: date_created
        status:
            type: string
            length: 255
        size:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
        location:
            type: string
            length: 255

    lifecycleCallbacks: {  }
