<?php

namespace ApiBundle\Repository;

/**
 * ApiKeysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKeysRepository extends \Doctrine\ORM\EntityRepository
{
}
