AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        username:
            type: string
            length: 255
            unique: true
        email:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        status:
            type: string
            length: 255
        admin:
            type: integer
            length: 255
        apiKey:
            type: string
            length: 255
            nullable: true
        tfaStatus:
            type: integer
            length: 255
        tfaSecret:
            type: string
            length: 255
            nullable: true
        serverUser:
            type: string
            length: 255
            nullable: true
        serverPassword:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
