ftp:
    resource: "@FtpBundle/Controller/"
    type:     annotation
    prefix:   /

whmcs:
    resource: "@WhmcsBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

server:
    resource: "@ServerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
